// src/pages/Tools.jsx
import React from 'react';
import './tools.css';
const Tools = () => {
  const tools = [
    {
      name: 'Fact Check Explorer',
      description: 'Search for fact-checked articles related to any claim using Google’s Fact Check tool.',
      link: 'https://toolbox.google.com/factcheck/explorer',
    },
    {
      name: 'Reverse Image Search',
      description: 'Verify image sources or find similar content using Google Reverse Image Search.',
      link: 'https://images.google.com/',
    },
    {
      name: 'Trusted News Sources',
      description: 'Browse through a curated list of reputable news outlets to compare narratives.',
      link: 'https://www.reuters.com/',
    },
    {
      name: 'Deepfake Detection Toolkit',
      description: 'Use tools to detect tampered or AI-generated videos and photos.',
      link: 'https://www.deepware.ai/',
    },
    {
      name: 'AI Detector for Content',
      description: 'Analyze text and determine if it was likely generated by an AI.',
      link: 'https://contentatscale.ai/ai-content-detector/',
    },
  ];

  return (
    <div className="App">
      <h1>🧰 Extra Tools & Resources</h1>
      <p style={{ fontSize: '1.1rem', marginBottom: '40px' }}>
        Leverage trusted tools to verify, fact-check, and explore authenticity of content.
      </p>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '30px', marginTop: '20px' }}>
        {tools.map((tool, idx) => (
          <div
            key={idx}
            className="result-card"
            style={{ textAlign: 'left', transition: '0.3s ease', cursor: 'pointer' }}
            onClick={() => window.open(tool.link, '_blank')}
          >
            <h2>{tool.name}</h2>
            <p>{tool.description}</p>
            <a href={tool.link} target="_blank" rel="noopener noreferrer">
              🔗 Visit Tool
            </a>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Tools;